{"message":"Something went wrong, try again!","success":false,"response":{"traceback":"Traceback (most recent call last):\n  File \"/home/GetLinkBackend/helpers/utils/advice.py\", line 25, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/recruiter/views.py\", line 473, in post\n    valid = validate_admin_and_invitee_email_domain(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/GetLinkBackend/helpers/reusable.py\", line 143, in validate_admin_and_invitee_email_domain\n    if company_domain != invitee_email_split[1]:\n                         ~~~~~~~~~~~~~~~~~~~^^^\nIndexError: list index out of range\n"}}